In [4]:
import numpy as np
import pickle
import pandas as pd
import matplotlib.pyplot as plt
import os
# from q_agent import *
# from fun_approx_agent import *
from collections import OrderedDict

In [13]:
grid = np.array([[0, 0, 2, 0, 0],
                 [0, 0, 0, 1, 0],
                 [0, 0, 0, 0, 0],
                 [0, 0, 0, 0, 0],
                 [0, 0, 1, 0, 0],
                 [0, 0, 0, 0, 0]])
print grid

[[0 0 2 0 0]
 [0 0 0 1 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 1 0 0]
 [0 0 0 0 0]]


In [40]:
def distance(p0, p1):
    return np.sqrt((p0[0] - p1[0])**2 + (p0[1] - p1[1])**2)

# cars = {'self': (92, 106, 16, 7), 'others': [(124, 86, 10, 4), (178, 64, 5, 3)]}

# self_coords = cars['self'][:2]
# others_coords = [coords[:2] for coords in cars['others'][:2]]
# print self_coords
# print others_coords




# distance(self_coords, others_coords)


cars_to_keep = 2  # number of cars to consider in grid.
car_coords = []
no_car_coords = [10, 0]  # default coords if not enough cars.


grid = np.array([[0, 0, 2, 0, 0],
                 [0, 0, 0, 0, 0],
                 [0, 1, 0, 0, 0],
                 [0, 0, 0, 0, 1],
                 [0, 0, 0, 0, 0],
                 [0, 0, 0, 0, 0]])

# Find car coordinates.
self_ = np.argwhere(grid == 2)[0]
others_all = np.argwhere(grid == 1)
print others_all

# Only keep closest cars.
dists = [(other, distance(self_, other)) for other in others_all]
others = [tup[0] for tup in sorted(dists, key=lambda tup: tup[1])[:cars_to_keep]]

# Create dummy entries for cars if there aren't enough on the grid.
cars_to_add = cars_to_keep - len(others)
for _ in range(cars_to_add):
    others.append(np.array(no_car_coords))
others_normed = [other - self_ for other in others]

print others_normed

[[2 1]
 [3 4]]
[array([ 2, -1]), array([3, 2])]


In [50]:
for other_normed in others_normed:
    print other_normed, other_normed[0] if abs(other_normed[1]) <= 2 else 11

[ 2 -1] 2
[3 2] 11


In [55]:
grid.shape

(6, 5)

In [56]:
# Flip left/right
print np.fliplr(grid)

[[0 0 2 0 0]
 [0 1 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 1 0 0]
 [0 0 0 0 0]]


In [101]:
print define_state(grid, 1, 1)
print '=' * 25
print define_state(grid, 2, 1)
print '=' * 25
print define_state(grid, 2, 2)

[[0 2 0]
 [0 0 1]]
[[0 2 0]
 [0 0 1]
 [0 0 0]]
[[0 0 2 0 0]
 [0 0 0 1 0]
 [0 0 0 0 0]]


In [5]:
np.random.uniform()

0.22839668574920524

In [10]:
np.random.choice([1, 2, 3])

3

In [13]:
 in [None]

False

In [15]:

[a for a in [1, 2, 3] if a != 1]

[2, 3]

In [14]:
tmp = [1, 2, 3]
np.random.shuffle(tmp)
print tmp

[2, 1, 3]


In [83]:
learning_file = '/afs/inf.ed.ac.uk/user/s16/s1667278/Desktop/rl-cw1/run/f4_s7/state_action_reward_dict.p'
with open(learning_file, 'r') as f:
    state_action_reward_dict = pickle.load(f)

Qs = []
ns = []
for Q, n in state_action_reward_dict.values():
    Qs.append(float(Q))
    ns.append(n)

Qs = []
ns = []
for key, value in state_action_reward_dict.iteritems():
    print 'state:\n{}\naction: {}\nQ: {}\nn: {}'.format(a.str2array(key[0]), key[1], value[0], value[1])
    
# np.mean([int(Q>0) for Q in Qs])
    
    
# plt.scatter(ns, Qs)
# plt.show()

# plt.hist(np.log(ns), 100)
# plt.show()

# plt.hist(np.log(Qs), 10)
# plt.show()

state:
[[0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]]
action: 11
Q: 2.17243254461e-08
n: 1
state:
[[0 2 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1]]
action: 1
Q: -0.0105550963484
n: 17
state:
[[0 0 0 0 0 2 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0]]
action: 5
Q: 3.78185436255e-06
n: 1
state:
[[0 0 0 0 2 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
action: 5
Q: 0.0
n: 1
state:
[[0 0 0 0 0 2 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
action: 12
Q: 0.0
n: 1
state:
[[0 0 1 0 0 0 2 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
action: 11
Q: 0.0683304735759
n: 41
state:
[[0 0 0 2 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 

In [52]:
grid

array([[0, 0, 2, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0]])

In [70]:
a = QAgent()

def flip_action(action):
    return {11: 12, 12: 11}.get(action, action)
    
for action in a.getActionsSet():
    print 'action: {}; new action: {}'.format(Action.toString(action), Action.toString(flip_action(action)))

action: ACCELERATE; new action: ACCELERATE
action: RIGHT; new action: LEFT
action: LEFT; new action: RIGHT
action: BREAK; new action: BREAK


In [77]:
state = a.define_state(grid)
print state
print a.str2array(state)
def flip_state(state):
    return a.array2str(np.fliplr(a.str2array(state)))
print flip_state(state)
print a.str2array(flip_state(state))

(6, 5)002000001000000000000010000000
[[0 0 2 0 0]
 [0 0 0 1 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 1 0 0]
 [0 0 0 0 0]]
(6, 5)002000100000000000000010000000
[[0 0 2 0 0]
 [0 1 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 1 0 0]
 [0 0 0 0 0]]


In [2]:
road = [[[107, 52], [108, 52], [110, 52], [112, 52], [113, 52], [115, 52], [117, 52], [118, 52], [120, 52], [122, 52], [124, 52]], [[104, 54], [106, 54], [108, 54], [110, 54], [112, 54], [114, 54], [116, 54], [118, 54], [120, 54], [122, 54], [125, 54]], [[102, 57], [104, 57], [107, 57], [110, 57], [112, 57], [115, 57], [118, 57], [120, 57], [123, 57], [126, 57], [129, 57]], [[99, 60], [102, 60], [105, 60], [108, 60], [112, 60], [115, 60], [118, 60], [122, 60], [125, 60], [128, 60], [132, 60]], [[95, 64], [99, 64], [103, 64], [107, 64], [111, 64], [115, 64], [119, 64], [123, 64], [127, 64], [131, 64], [136, 64]], [[91, 68], [95, 68], [100, 68], [105, 68], [110, 68], [115, 68], [119, 68], [124, 68], [129, 68], [134, 68], [139, 68]], [[87, 73], [92, 73], [98, 73], [103, 73], [109, 73], [115, 73], [120, 73], [126, 73], [131, 73], [137, 73], [143, 73]], [[83, 78], [89, 78], [96, 78], [102, 78], [109, 78], [115, 78], [122, 78], [128, 78], [135, 78], [141, 78], [148, 78]], [[78, 84], [85, 84], [93, 84], [100, 84], [108, 84], [115, 84], [123, 84], [130, 84], [138, 84], [145, 84], [153, 84]], [[71, 91], [79, 91], [88, 91], [97, 91], [105, 91], [114, 91], [123, 91], [131, 91], [140, 91], [149, 91], [158, 91]], [[63, 100], [73, 100], [83, 100], [93, 100], [104, 100], [114, 100], [124, 100], [135, 100], [145, 100], [155, 100], [166, 100]], [[53, 112], [65, 112], [77, 112], [90, 112], [102, 112], [115, 112], [127, 112], [139, 112], [152, 112], [164, 112], [177, 112]]]

In [16]:
np.mean([x for x, y in road[0][4:6]]) - 114

0.0

In [17]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [64]:
state_action = OrderedDict()

state_action['a'] = 1
state_action['b'] = 2
state_action['c'] = 3
state_action['d'] = 4



In [67]:
state_action.keys()

['a', 'b', 'c', 'd']

In [72]:
state_action.values()

[1, 2, 3, 4]

In [71]:
weights[state_action.keys().index('action_accel')] = 1

ValueError: 'e' is not in list

In [76]:
np.random.normal(0, 1, 18)

array([-0.75994288,  0.64898956,  0.92299866,  0.48010411,  0.39416803,
       -1.38766386,  0.78757189, -0.18073586,  0.8948755 ,  0.44364744,
        0.71082141,  0.63931578, -1.42155842, -0.78376448,  0.66479019,
        0.33132329, -1.35117696,  0.78125589])

In [18]:
main_path = '//Users/sipola/Google Drive/education/coursework/graduate/edinburgh/rl/rl-cw2/rl-cw2'
# main_path = '/afs/inf.ed.ac.uk/user/s16/s1667278/Desktop/rl-cw2'
weights_all_path = os.path.join(main_path, 'run/initial/weights_all.p')
weights_path = os.path.join(main_path, 'run/initial/weights.p')
with open(weights_all_path, 'r') as input_file:
    weights_all = pickle.load(input_file)
with open(weights_path, 'r') as input_file:
    weights = pickle.load(input_file)
feature_names = [
    'dist_from_center',
    'toward_center',
    'away_from_center',
    'action_accel',
    'car1_ydist',
    'car1_xdist',
    'toward_car1',
    'away_from_car1',
    'close_to_bump_accel',
    'close_to_bump_left_or_right',
    'toward_car2',
    'away_from_car2'
]

df = pd.DataFrame(weights_all)
df.columns = feature_names
df.to_csv(os.path.join(main_path, 'run/initial/weights_all.csv'), index=False)


weights_df = pd.DataFrame(weights)
weights_df['1'] = feature_names
weights_df.columns = ['Value', 'Feature']
weights_df.to_csv(os.path.join(main_path, 'run/initial/weights.csv'), index=False)